name: ArmorStandTool
api-version: 1.13
version: ${project.version}
author: WolfyScript
depend:
  - WolfyUtilities

main: me.wolfyscript.armorstandtool.ArmorStandTool

commands:
  ast:
    description: just a description
