items:
  none:
    toggle_button_off:
      name: "&4inaktiv"
      help:
        - ""
      lore:
        - ""
    toggle_button_on:
      name: "&aaktiv"
      help:
        - ""
      lore:
        - ""
  main_menu:
    base_plate:
      name: "&a&lBodenplatte"
      help:
        - ""
      lore:
        - ""
    arms:
      name: "&a&lArme"
      help:
        - ""
      lore:
        - ""
    small_stand:
      name: "&a&lVerkleinert"
      help:
        - ""
      lore:
        - ""
    no_gravity:
      name: "&a&lSchwerkraft"
      help:
        - ""
      lore:
        - ""
    invisible:
      name: "&a&lUnsichtbar"
      help:
        - ""
      lore:
        - ""
    display_name:
      name: "&a&lName Sichtbar"
      help:
        - ""
      lore:
        - "Der name kann mit einem Nametag gesetzt werden."
    rotation_left_arm:
      name: "&a&lDrehung Linker Arm"
      help:
        - ""
      lore:
        - ""
    rotation_left_leg:
      name: "&a&lDrehung Linkes Bein"
      help:
        - ""
      lore:
        - ""
    rotation_right_arm:
      name: "&a&lDrehung Rechter Arm"
      help:
        - ""
      lore:
        - ""
    rotation_right_leg:
      name: "&a&lDrehung Rechtes Bein"
      help:
        - ""
      lore:
        - ""
    rotation_body:
      name: "&a&lKörperdrehung"
      help:
        - ""
      lore:
        - ""
    rotation_head:
      name: "&a&lKopfdrehung"
      help:
        - ""
      lore:
        - ""
    position:
      name: "&a&lPosition"
      help:
        - ""
      lore:
        - ""
    helmet:
      name: "&a&lHelm"
      help:
        - ""
      lore:
        - ""
    chestplate:
      name: "&a&lBrustpanzer"
      help:
        - ""
      lore:
        - ""
    leggings:
      name: "&a&lHose"
      help:
        - ""
      lore:
        - ""
    boots:
      name: "&a&lSchuhe"
      help:
        - ""
      lore:
        - ""
    left_hand:
      name: "&a&lLinke Hand"
      help:
        - ""
      lore:
        - ""
    right_hand:
      name: "&a&lRechte Hand"
      help:
        - ""
      lore:
        - ""
  settings:
    add_001:
      name: "+0.01"
      lore:
        - "Shift+Klick: +0.00001"
      help:
        - ""
    add_01:
      name: "+0.1"
      lore:
        - "Shift+Klick: +0.0001"
      help:
        - ""
    add_1:
      name: "+1.0"
      lore:
        - "Shift+Klick: +0.001"
      help:
        - ""
    remove_001:
      name: "-0.01"
      lore:
        - "Shift+Klick: -0.00001"
      help:
        - ""
    remove_01:
      name: "-0.1"
      lore:
        - "Shift+Klick: -0.0001"
      help:
        - ""
    remove_1:
      name: "-1.0"
      lore:
        - "Shift+Klick: -0.001"
      help:
        - ""
    x_pos:
      name: "x = %VALUE%"
      help:
        - ""
    y_pos:
      name: "y = %VALUE%"
      help:
        - ""
    z_pos:
      name: "z = %VALUE%"
      help:
        - ""
    x_value:
      name: "x = %VALUE%"
      lore: []
      help:
        - ""
    y_value:
      name: "y = %VALUE%"
      lore: []
      help:
        - ""
    z_value:
      name: "z = %VALUE%"
      lore: []
      help:
        - ""
    yaw:
      name: "yaw = %VALUE%"
      lore:
        - "Mit Klick auf 0 Setzen"
      help:
        - ""
    free_edit:
      name: "Frei bearbeiten"
      lore:
        - ""
      help:
        - ""
    back:
      name: "&a&lZurück"
      lore:
        - ""
      help:
        - ""
inventories:
  main_menu: "Rüstungsständer bearbeiten"
  settings: "Rüstungsständer bearbeiten"
msg:
  free_edit:
    cancelled: "Freie Bearbeitung beendet"
  edit:
    open:
      cancelled: "&cDu darfst diesen Rüstungsständer nicht bearbeiten!"
  reload:
    complete: "&aErfolgreich neu geladen!"
