items:
  none:
    toggle_button_off:
      name: "&4Aus"
      help:
        - ""
      lore:
        - ""
    toggle_button_on:
      name: "&aAn"
      help:
        - ""
      lore:
        - ""

  main_menu:
    base_plate:
      name: "&6Bodenplatte"
      help:
        - ""
      lore:
        - "<empty>"
    arms:
      name: "&6Arme"
      help:
        - ""
      lore:
        - "<empty>"
    small_stand:
      name: "&6Kleiner Stand"
      help:
        - ""
      lore:
        - "<empty>"
    no_gravity:
      name: "&6Gravitation"
      help:
        - ""
      lore:
        - "<empty>"
    invisible:
      name: "&6Sichtbar"
      help:
        - ""
      lore:
        - "<empty>"
    display_name:
      name: "&6Name sichtbar"
      help:
        - ""
      lore:
        - "Der Name kann mit einem Namensschild geändert werden!"
    rotation_left_arm:
      name: "&6Linker Arm"
      help:
        - ""
      lore:
        - ""
    rotation_left_leg:
      name: "&6Linkes Bein"
      help:
        - ""
      lore:
        - ""
    rotation_right_arm:
      name: "&6Rechter Arm"
      help:
        - ""
      lore:
        - ""
    rotation_right_leg:
      name: "&6Rechtes Bein"
      help:
        - ""
      lore:
        - ""
    rotation_body:
      name: "&6Körper drehen"
      help:
        - ""
      lore:
        - ""
    rotation_head:
      name: "&6Kopf drehen"
      help:
        - ""
      lore:
        - ""
    position:
      name: "&6Position"
      help:
        - ""
      lore:
        - ""
    helmet:
      name: "&6Helm"
      help:
        - ""
      lore:
        - ""
    chestplate:
      name: "&6Brustplatte"
      help:
        - ""
      lore:
        - ""
    leggings:
      name: "&6Hose"
      help:
        - ""
      lore:
        - ""
    boots:
      name: "&6Schuhe"
      help:
        - ""
      lore:
        - ""
    left_hand:
      name: "&6Linke Hand"
      help:
        - ""
      lore:
        - ""
    right_hand:
      name: "&6Rechte Hand"
      help:
        - ""
      lore:
        - ""

  settings:
    add_001:
      name: "+0.01"
      lore:
        - "Shift+Click: +0.00001"
      help:
        - ""
    add_01:
      name: "+0.1"
      lore:
        - "Shift+Click: +0.0001"
      help:
        - ""
    add_1:
      name: "+1.0"
      lore:
        - "Shift+Click: +0.001"
      help:
        - ""
    remove_001:
      name: "-0.01"
      lore:
        - "Shift+Click: -0.00001"
      help:
        - ""
    remove_01:
      name: "-0.1"
      lore:
        - "Shift+Click: -0.0001"
      help:
        - ""
    remove_1:
      name: "-1.0"
      lore:
         - "Shift+Click: -0.001"
      help:
        - ""
    x_pos:
      name: "x = %VALUE%"
      lore:
        - "Klick um auf 0 zu setzen"
      help:
        - ""
    y_pos:
      name: "y = %VALUE%"
      lore:
        - "Klick um auf 0 zu setzen"
      help:
        - ""
    z_pos:
      name: "z = %VALUE%"
      lore:
        - "Klick um auf 0 zu setzen"
      help:
        - ""
    yaw:
      name: "yaw = %VALUE%"
      lore:
        - "Klick um auf 0 zu setzen"
      help:
        - ""
    free_edit:
      name: "Frei bearbeiten"
      lore:
        - ""
      help:
        - ""
    back:
      name: "Zurück"
      lore:
        - ""
      help:
        - ""

inventories:
  main_menu: "ArmorStand bearbeiten"
  settings: "ArmorStand bearbeiten"

msg:
  free_edit:
    cancelled: "Freies Bearbeiten wurde abgebrochen!"
  edit:
    open:
      cancelled: "&4Du kannst diesen Rüstungsständer nicht bearbeiten!"