name: ArmorStandTool
api-version: 1.13
version: 0.1.1
author: WolfyScript
depend:
  - WolfyUtilities

main: me.wolfyscript.armorstandtool.ArmorStandTool

commands:
  ast:
    description: just a description